version: "2"

services:
  web:
    build: php7/.
#    build: php56/.
#    image: skilldlabs/php:7
    ports:
      - "8081:80"
    volumes:
      - ./drupal:/srv:Z
      - ./scripts:/scripts
      - ./src:/src
    links:
      - mysql:mysql
      - mailhog:mailhog
    depends_on:
      - mysql
      - mailhog
    restart: always
    command: php -t /srv -S 0.0.0.0:80 .ht.router.php
    networks:
      - back
      - front
    environment:
      WORKFLOW: profile
#      WORKFLOW: sql
      DRUPAL: 8
#      DRUPAL: 7

  mysql:
    image: percona:5.7
    volumes:
      - ./db:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
      MYSQL_ROOT_PASSWORD: d8root
    restart: always
    networks:
      - back

  mailhog:
    image: diyan/mailhog
    restart: always
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
