web:
  build: .
#  image: php7
  ports:
    - "8081:80"
  volumes:
    - ./drupal:/srv
  links:
    - mysql:mysql
    - mailhog:mailhog
  restart: always
  command: php -t /srv -S 0.0.0.0:80 .ht.router.php

mysql:
  image: percona:5.6.27
  volumes:
  - ./db:/var/lib/mysql
  environment:
    MYSQL_DATABASE: d8
    MYSQL_USER: d8
    MYSQL_PASSWORD: d8
    MYSQL_ROOT_PASSWORD: d8root
  restart: always

mailhog:
  image: diyan/mailhog
  ports:
    - "1025:1025"
    - "8025:8025"
  restart: always

